### ISSUE TITLE
能支持自动上传到腾讯云cos图床吗

### ISSUE THREAD

**Issue by leeyiding** [Thobian/typora-plugins-win-img#1]
平时写博客用的都是腾讯云cos作为图床，之前用的是cos客户端，后来用了PicGo，支持拖拽图片上传到cos并复制markdown链接，想问一问这个项目有没有办法自动上传到腾讯云cos

**Comment by Thobian** [comment]
可以实现的。

将项目中 `upload.php` 上传到本地磁盘换成上传到cos就好。COS有提供API，好像也有提供对应SDK 对接下应该挺快的

**Comment by Thobian** [comment]
> 平时写博客用的都是腾讯云cos作为图床，之前用的是cos客户端，后来用了PicGo，支持拖拽图片上传到cos并复制markdown链接，想问一问这个项目有没有办法自动上传到腾讯云cos

目前已经支持 上传到腾讯云COS，操作文档还未更新。想尝新 可以看下 `upload.js` 源码，可以快速修改为你自己的 cos 空间。

```
var config = {
    target:'tencent',
    tencent : {
        Bucket: 'bucket-name',  // 对象存储->存储桶列表(存储桶名称就是Bucket)
        SecretId: 'SecretId',       // 访问控制->用户->用户列表->用户详情->API密钥 下查看
        SecretKey: 'SecretKey', // 访问控制->用户->用户列表->用户详情->API密钥 下查看
        Region: 'Region',          // 对象存储->存储桶列表(所属地域中的英文就是Region)
        folder: 'typora',             // 可以把上传的图片都放到这个指定的文件夹下
    },
};
$.image.init(config);
```
