### ISSUE TITLE
上传成功自动删除本地图片-增加paste事件-图片上传失败时设置背景

### ISSUE THREAD

**Issue by Byzero512** [Thobian/typora-plugins-win-img#14]
本地图片自动存放在C盘.
占空间, 上传成功应该自动删除

**Comment by Thobian** [comment]
我这个插件应该做不到这个功能，插件只是一些js代码 做不到删除你本地文件功能的

**Comment by Byzero512** [comment]
> 我这个插件应该做不到这个功能，插件只是一些js代码 做不到删除你本地文件功能的

嗯. 确实. 我写个脚本启动算了, 每次启动清空文件夹
有个地方
            setting.element.
                parent('span[md-inline="image"]').
                data('src', url).
                find('.md-image-src-span').
                html(url);
你那个data('src',url)应该是想把span[md-inline="image"]这个标签里面的data-src属性修改成url把.
但是你这种写法似乎没有改变?

**Comment by Byzero512** [comment]
`
        $('#write').on('click', 'img', function(e){
            try{
                var src = e.target.src;
                // haved upload to github
                if( /^(https?:)?\/\//i.test(src) ){
                    // console.log('The image already upload to server, url:' + src);
                    return false;
                }
                setting.element = element = $(e.target);
                var doing = element.attr(locked)=='1';
                if( doing ){
                    // console.log('uploading...');
                    return false;
                }else{
                    element.attr(locked, '1');
                }
                // console.log('<div id="' + noticeEle + '" style="position:fixed;height:40px;line-height:40px;padding:0 15px;overflow-y:auto;overflow-x:hidden;z-index:10;color:#fff;width:100%;display:none;"></div>');
                $('content').prepend('<div id="'+noticeEle+'" style="position:fixed;height:40px;line-height:40px;padding:0 15px;overflow-y:auto;overflow-x:hidden;z-index:10;color:#fff;width:100%;display:none;"></div>');
                //转换成普通的图片地址
                //src = src.substring(8, src.indexOf('?last'));
                loadImgAndSend(src);
            }
            catch(e){console.log(e);};
        });
        $('#write').on('paste', function (e) {
            try {
                setTimeout(function(){
                    element = $(e.target);
                    if (element.has("img").length>0){
                        setting.element.attr(locked, '1');
                        setting.element = element.find('img');
                        src = setting.element.attr("src");
                        loadImgAndSend(src);
                    }
                },512);
            }
            catch (e) { console.log(e); };
        });
`

**Comment by Thobian** [comment]
问题1：不是的，就是为了替换你在typora在所见即所得视图下的内容

问题2：用`mouseleave`只是为了让失败时再次上传动作触发的更自然点，同时也有做防重复上传的判断，如果换成 paste 是为了追求性能我觉得可以再考虑下（毕竟相对word等编辑器来说typora应该说很轻量了）

**Comment by Byzero512** [comment]
> 问题1：不是的，就是为了替换你在typora在所见即所得视图下的内容
> 
> 问题2：用`mouseleave`只是为了让失败时再次上传动作触发的更自然点，同时也有做防重复上传的判断，如果换成 paste 是为了追求性能我觉得可以再考虑下（毕竟相对word等编辑器来说typora应该说很轻量了）

嗯, 换成paste是因为mouseleave事件触发有些不太稳定, 例如你粘贴了一张图片, 然后ctrl+W退出, 这样子似乎就不会触发.

**Comment by Thobian** [comment]
从这个角度看可以，多监听个paste事件 [斜眼]

**Comment by Byzero512** [comment]
另外建议对于上传失败的图片, 加个红色边框或者背景, 提示这张图片上传失败.

**Comment by Byzero512** [comment]
https://github.com/Byzero512/CodeRepo/tree/master/typora-auto-upload-img
我改了一下你的代码:
1. 添加删除本地图片功能
2. 删除mouseleave事件,添加paste事件
3. 上传成功失败的提示: 上传成功不提示, 上传失败将图片背景染红, 不在顶部出现错误提示.

**Comment by Thobian** [comment]
> https://github.com/Byzero512/CodeRepo/tree/master/typora-auto-upload-img
> 我改了一下你的代码:
> 
> 1. 添加删除本地图片功能
> 2. 删除mouseleave事件,添加paste事件
> 3. 上传成功失败的提示: 上传成功不提示, 上传失败将图片背景染红, 不在顶部出现错误提示.

多谢
1. 删除本地图片的功能暂时还么打算提供，剪切板截图一般删掉没啥，但有些非剪切板的图片如果也会不知不觉被删除感觉还是不太好;
2. paste事件会考虑加上，mouseleave大概也还会保留；
3. 第三点挺好的，后续版本也会借用你的思路；

**Comment by Byzero512** [comment]
> > https://github.com/Byzero512/CodeRepo/tree/master/typora-auto-upload-img
> > 我改了一下你的代码:
> > 
> > 1. 添加删除本地图片功能
> > 2. 删除mouseleave事件,添加paste事件
> > 3. 上传成功失败的提示: 上传成功不提示, 上传失败将图片背景染红, 不在顶部出现错误提示.
> 
> 多谢
> 
> 1. 删除本地图片的功能暂时还么打算提供，剪切板截图一般删掉没啥，但有些非剪切板的图片如果也会不知不觉被删除感觉还是不太好;
> 2. paste事件会考虑加上，mouseleave大概也还会保留；
> 3. 第三点挺好的，后续版本也会借用你的思路；

当paste事件触发, 判断是图片的话给<img>添加一个属性标明图片来自粘贴板即可, 上传成功删除该属性, 上传失败不删除该属性.
