### ISSUE TITLE
希望能够支持上传前自动压缩图片的功能

### ISSUE THREAD

**Issue by Holldean** [Thobian/typora-plugins-win-img#15]
4k屏截出来的图片占的空间太大了，如果能够在上传之前自动发到squoosh.app之类的网站压缩图片就更好了，或者直接把压缩算法集成在插件里面

**Comment by Thobian** [comment]
还不错的建议，后面我找找开源的js压缩算法看是否能比较快捷的加上。

**Comment by ITCJ** [comment]
如果是阿里云OSS可以设置自动压缩和添加水印

**Comment by Thobian** [comment]
最新master代码已经支持  本地图片压缩，具体使用请查看 README
