### ISSUE TITLE
工具真的非常好用  有个问题能否更改返回图片网络地址呢 Github+jsDelivr 这样图片加载更快 体验更好

### ISSUE THREAD

**Issue by chenhaishun** [Thobian/typora-plugins-win-img#16]
在使用的时候发现存在一个问题 
图片在上传到github图床后 下次再打开文件的时候 文件中的图片加载非常慢 大部分情况下都会挂掉 
我们可以不可以更改返回地址的路径 使用jsDelivr加速图片加载呢？（用 jsdelivr 来访问 github的资源）
举个例子：
上传路径是：https://raw.githubusercontent.com/XXX/test_pic/master/XXX.png
下载路径是：https://cdn.jsdelivr.net/gh/XXX/test_pic@master/XXX.png
我手动测试过 这样图片加载会非常快
但是我js脚本不会改......亲爱的作者或者各位大佬有人知道关于返回图片网址怎么改吗？谢谢了！

**Comment by Thobian** [comment]
你要的这个功能可以实现，但感觉不是大众的需求。
而且最重要的问题是，镜像站点是否像github一样长期、稳定的运营下去，如果镜像站点哪天关了会导致你的图片没法访问到。（当然`jsdelivr`还是挺稳定的）

其实，你要的这个功能就是做一些字符串操作，如果你对这个需求很强烈，不妨试试自己尝试改了试试，相信你可以的~

**Comment by chenhaishun** [comment]
非常感谢你的回复，因为国内访问github加载资源速度很慢，甚至有的时候直接挂掉，关于js脚本，因为之前没有这个方面的基础，尝试过改动但是一直不成功，还望作者能指点一二，在此谢过了！

**Comment by Thobian** [comment]
最新版增加了这个功能，但是默认是关闭的。
升级最新版后打开 ` jsDelivrCND` 开关即可走 jsdelivr 访问图片了。

**Comment by chenhaishun** [comment]
非常感谢！谢谢！
