### ISSUE TITLE
识别图片本地地址和网络地址的功能好像失效了

### ISSUE THREAD

**Issue by Asunfly** [Thobian/typora-plugins-win-img#17]
【如图片原本就是网络图片地址，插件将保持原链接不处理（正则匹配：/^(https?:)?\/\//i）；】
现在遇到的情况是，不管图片是本地还是在线的地址，均会上传到指定的服务器

**Comment by Thobian** [comment]
大概是插件在你的typora版本工作不正常导致的，应该不是正则的问题。你可以 `shift+f12` 打开控制台（console）然后操作文档图片后将日志截图发来看下。

**Comment by Asunfly** [comment]
![image](https://user-images.githubusercontent.com/34542913/75643945-8f1d0d00-5c7b-11ea-80e3-e006cfc37a4e.png)

**Comment by Thobian** [comment]
我理解是没啥问题，那个提醒只是告诉你图片已经上传了（可能是因为这次上传的、也可能是本来就是个网络图片）。
如果你觉得已经是网络图片还再次被上传，你可以切到 `network` 下查看是否有上传图片的网络请求发生，应该是不会有的

**Comment by Asunfly** [comment]
![示例](https://user-images.githubusercontent.com/34542913/75837476-ec41cb80-5dff-11ea-82ba-85312363483d.gif)
大概的问题是这样，复制网络图片地址=>粘贴后转为本地地址=>转为自己配置的服务器地址

**Comment by Thobian** [comment]
![image](https://user-images.githubusercontent.com/3353162/75883467-027e7480-5e5e-11ea-843c-113d9d0cb84b.png)
可能是你打开了这个开关

**Comment by Asunfly** [comment]
哇果然是的，把第二个勾掉就好了，非常感谢

**Comment by Thobian** [comment]
不客气，

**Comment by aoeyiha** [comment]
服务器响应解析失败是因为git配置不对吗？还是网络的问题啊

**Comment by XuanduoZ** [comment]
图片成功上传到github之后就会变成一串串的代码，永远显示图片下载失败是怎么回事？

**Comment by Thobian** [comment]
> 服务器响应解析失败是因为git配置不对吗？还是网络的问题啊

@aoeyiha 尽量截图，你这描述我没法给你确定原因。

**Comment by Thobian** [comment]
> 图片成功上传到github之后就会变成一串串的代码，永远显示图片下载失败是怎么回事？

@XuanduoZ 在一个issue下咨询就好了，不用多处发。在另外个问题下回答了

**Comment by hexi519** [comment]
> ![image](https://user-images.githubusercontent.com/3353162/75883467-027e7480-5e5e-11ea-843c-113d9d0cb84b.png)
> 可能是你打开了这个开关
![image](https://user-images.githubusercontent.com/32733547/88636170-241d1880-d0eb-11ea-95f2-e12824a53f74.png)
我按照这样设置，会先在本地存储一遍，再上传。改成插入图片时无特殊操作就可以直接上传了。

**Comment by PuppetDD** [comment]
0.9.92等新版本中图片重复上传，Shift+F12发现是因为每次上传替换图片链接后，文件没有自动保存，切换到其他应用后，图片链接又变成了本地路径，所以会触发再次上传，解决方法：可以ctrl+s，手动保存一次（设置自动保存没用，不会触发这frame.js: presentedItemChanged，这个是Typora自带的JS）
![image](https://user-images.githubusercontent.com/48472292/106702125-cbdb4c00-6622-11eb-9bdc-5f29c23e9140.png)

**Comment by dongbingliu** [comment]
版本 Windows : 0.10.9 (beta)

所有的图片选项全部取消, 但切换应用再切换回来会自动再次上传
![image](https://user-images.githubusercontent.com/7981299/124347432-5ac2b380-dc17-11eb-8560-6ee8584920dd.png)

**Comment by dongbingliu** [comment]
> 0.9.92等新版本中图片重复上传，Shift+F12发现是因为每次上传替换图片链接后，文件没有自动保存，切换到其他应用后，图片链接又变成了本地路径，所以会触发再次上传，解决方法：可以ctrl+s，手动保存一次（设置自动保存没用，不会触发这frame.js: presentedItemChanged，这个是Typora自带的JS）
> ![image](https://user-images.githubusercontent.com/48472292/106702125-cbdb4c00-6622-11eb-9bdc-5f29c23e9140.png)

版本 Windows : 0.10.9 (beta) 版本保存之后, 切换应用还是会自动上传

**Comment by SingAurora** [comment]
我也发现了会重复上传, 必须手动保存一次
