### ISSUE TITLE
请求增加 Gitee（码云）上传方式

### ISSUE THREAD

**Issue by txyyh** [Thobian/typora-plugins-win-img#19]
众所周知 GitHub 近期访问难度逐渐变大，后面再以 GitHub 做图床使用难度很可能会加大，即使现在有 jsdelivr 加持，后期也难保使用稳定。
因此建议增加 Gitee 上传方式。国内项目明显和谐的可能性极小，上传访问速度也会大大加快，并且一样免费+无需自建服务器。
自己曾打算尝试在 GitHub 上传方式基础上修改但无奈能力不过关。。。

**Comment by renshen052** [comment]
我fork了这个项目，增加了码云，提交了rp，等通过了

**Comment by gugugubo** [comment]
@renshen052  兄弟，你那个怎么配置啊，你没说清楚啊

**Comment by renshen052** [comment]
> @renshen052 兄弟，你那个怎么配置啊，你没说清楚啊
第一步：登录码云
第二步：创建一个公开的仓库 例如： img-gitee
第三步：访问 https://gitee.com/profile/personal_access_tokens 生成token
![image](https://user-images.githubusercontent.com/38830951/75832317-e690b980-5df0-11ea-9a64-a318d927933a.png)
第四步：配置
![image](https://user-images.githubusercontent.com/38830951/75832450-2f487280-5df1-11ea-85de-e934e33c8fd5.png)
token 是你刚刚申请的令牌

**Comment by txyyh** [comment]
@renshen052 您好，请问最后的配置这样对吗
··· JavaScript
$.image.init({
    target:'gitee',
    gitee:{
        message : 'add image' 
        brance : 'master'
        Token : 'xxxxxxxxxxxxxxxxxxx', 
        userName : 'nickname',                                           
        repositorie : 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',      
        Filepath : 'typora',                                                               
    }
});
···

**Comment by renshen052** [comment]
> @renshen052 您好，请问最后的配置这样对吗
> 
> ```js
> $.image.init({
>     target:'gitee',
>     gitee:{
>         message : 'add image' 
>         branch : 'master'
>         token : 'xxxxxxxxxxxxxxxxxxx', 
>         userName : 'nickname',                                           
>         repositorie : 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',      
>         Filepath : 'typora',                                                               
>     }
> });
> ```

你找错地方了吧，配置项要在 开头的 var setting = {  .......}  里面找 gitee

**Comment by txyyh** [comment]
@renshen052 感谢，是之前写错了上面的配置，提示错误才开始改下面的，多谢

**Comment by gugugubo** [comment]
@renshen052 真心感谢，已经搞定了，很棒！！！

**Comment by Thobian** [comment]
已合入master 暂未更新readme  有需要的可以根据 @renshen052 博客的说明先使用起来

**Comment by roytaJ** [comment]
期待更新readme啊

**Comment by Thobian** [comment]
> 期待更新readme啊

已经更新，拉最新的代码。
