### ISSUE TITLE
图片重复上传的问题

### ISSUE THREAD

**Issue by shy-share** [Thobian/typora-plugins-win-img#22]
即使图片已经存到了图床上，但是再次打开会提示再次下载那些图片，会造成图床资源的浪费，我认为可以在自动上传到图床之前，判断一下 图片的路径是不是以http这种开头的，这样是不是就可以避免我说的这种情况了

**Comment by Thobian** [comment]
看下是不是打开了这个设置开关导致的：https://github.com/Thobian/typora-plugins-win-img/issues/17

**Comment by shy-share** [comment]
好的，建议把这些注意事项，都放在最开始看的那里，让用户可以非常清楚哪些点需要注意

**Comment by Thobian** [comment]
readme注意事项已更新
