### ISSUE TITLE
大佬，可以修复下在最新0.9.86版本上使用的bug吗

### ISSUE THREAD

**Issue by nssiwi** [Thobian/typora-plugins-win-img#28]
偏好设置打不开了

**Comment by Thobian** [comment]
根据这[issue](https://github.com/Thobian/typora-plugins-win-img/issues/5)操作，不要覆盖应该是不会有问题的。覆盖的方式不可能修复，window.html文件是工具作者写的，他想怎么改就怎么改，我们只能基于他的修改来自己手动修改
