### ISSUE TITLE
图片可以上传到github之后，可以在github上看，但是无法在本地显示

### ISSUE THREAD

**Issue by shy-share** [Thobian/typora-plugins-win-img#31]
![Snipaste_2020-06-07_20-58-32](https://user-images.githubusercontent.com/50973219/83969841-ce0ad080-a904-11ea-809a-22756721bf8a.png)
![Snipaste_2020-06-07_20-59-58](https://user-images.githubusercontent.com/50973219/83969843-cfd49400-a904-11ea-81da-7cd6db33c45a.png)
感觉原因是超时了，我之前用阿里云是可以在本地显示的

**Comment by shy-share** [comment]
阿里云现在也不可以在本地显示了

**Comment by Thobian** [comment]
> ![Snipaste_2020-06-07_20-58-32](https://user-images.githubusercontent.com/50973219/83969841-ce0ad080-a904-11ea-809a-22756721bf8a.png)
> ![Snipaste_2020-06-07_20-59-58](https://user-images.githubusercontent.com/50973219/83969843-cfd49400-a904-11ea-81da-7cd6db33c45a.png)
> 感觉原因是超时了，我之前用阿里云是可以在本地显示的

这个是上传成功了，但由于 地址被墙所以显示不出来。如果有VPN 连上就可以显示了。阿里云要具体看下错误信息

**Comment by shy-share** [comment]
好的
