### ISSUE TITLE
图片上传成功之后，本地的md文件中的图片就显示不出来了，如图！

### ISSUE THREAD

**Issue by XuanduoZ** [Thobian/typora-plugins-win-img#33]
https://imgchr.com/i/NVUvCV

**Comment by XuanduoZ** [comment]
csdn显示：外链防盗机制
https://imgchr.com/i/NVaWqJ

**Comment by Thobian** [comment]
这种一般都是  githubusercontent.com 这个域被强了
如果一定要放到github上 可以试下打开 cdn功能，如何打开：在readme的 **插件配置->上传到Github——推荐** 中有说明
当然也可以放到国内码云上，这样一般不会有问题，具体差异以及有什么坑都 仔细阅读readme基本都有说明

**Comment by XuanduoZ** [comment]
@Thobian 大佬就是大佬，开了CDN之后立刻就好了！！！牛逼！！！！
