### ISSUE TITLE
关于设置腾讯云COS无法传到指定文件夹的问题

### ISSUE THREAD

**Issue by SPY-xxx** [Thobian/typora-plugins-win-img#34]
![image](https://user-images.githubusercontent.com/17687454/85720079-aac48b80-b722-11ea-9860-b804c2464f9a.png)
readme.md内容需修改 **'folder'->'Folder'** ，不然程序判断文件夹名字为undefined

**Comment by Thobian** [comment]
谢谢反馈，已更新readme
