### ISSUE TITLE
上传之前还是会在本地存储一遍

### ISSUE THREAD

**Issue by hexi519** [Thobian/typora-plugins-win-img#37]
您好！我这边成功之后发现图片上传之前会在本地存储一遍，希望之后的版本更新可以加一个自动删除功能，谢谢~

**Comment by Thobian** [comment]
https://github.com/Thobian/typora-plugins-win-img/issues/17#issuecomment-594518628
你看下是不是跟这个issue反馈的问题类似，如果不是 最好能提供个“动图” 复现下bug， 我自己在使用过程中貌似没遇到过这问题

**Comment by hexi519** [comment]
感谢，已解决！

**Comment by hexi519** [comment]
很抱歉，我发现并没有解决，修改了偏好设置之后，图片存储到新的文件夹去了。
我的问题如下：

**Comment by hexi519** [comment]
你好！我发现偏好设置中设置成无特殊操作之后，还是有图片缓存（之前设置的是上传文件，图片存到typora的安装目录里面去了），只不过换到系统的roaming文件中去了。我目前采取的方式是自己写个脚本定时清理。

![操作演示](https://user-images.githubusercontent.com/32733547/88638438-12894000-d0ee-11ea-83de-5c0f1dd5945d.gif)

**Comment by Thobian** [comment]
@hexi519 你截图后粘贴也是会有对应临时文件产生的，这个是否用这个插件没什么关系 。你要是在意这种临时文件 就像你说的自己写个脚本、或者电脑上有什么垃圾清理工具弄下就好了

**Comment by hexi519** [comment]
好的，万分感谢！
