### ISSUE TITLE
覆盖配置文件后，偏好设置能打开吗？

### ISSUE THREAD

**Issue by PowerDi** [Thobian/typora-plugins-win-img#5]
覆盖配置文件后，偏好设置打开似乎没有反应

**Comment by Thobian** [comment]
目前我本地 0.9.77(beta) 版本是可以正常打开偏好设置的，如果存在这个问题，可以尝试通过下面的步奏解决：
1. 可以把备份下来的 `window.html` 文件恢复回去。
2. 然后手动编辑恢复回去的文件，搜索`<script src="./app/window/frame.js" defer="defer"></script>` 在其后面加上一行：`<script src="./plugins/image/upload.js" defer="defer"></script>` 然后再试试是否能恢复正常。

注：readme中覆盖 `window.html`  只是为了引入 `./plugins/image/upload.js` 文件，但不同版本window.html文件可能存在一些差异，确实 有可能出现你说的这个问题。

**Comment by PowerDi** [comment]
经测试 0.9.68是可以打开偏好设置的。而0.9.81是无法打开的，与版本强相关

**Comment by dongbingliu** [comment]
0.981 不能打开偏好设置, 估计是 Window.html 覆盖引起的, 可以告知修改方法,而不是直接替换windows.html

**Comment by Thobian** [comment]
> 0.981 不能打开偏好设置, 估计是 Window.html 覆盖引起的, 可以告知修改方法,而不是直接替换windows.html

readme中已更新

**Comment by PowerDi** [comment]
Fixed problem.

**Comment by Mr-Nobody-li** [comment]
2020-3-11最新版本打不开偏好，windows.html直接覆盖掉了找不到了怎么办

**Comment by nssiwi** [comment]
0.9.86版本又不行了

**Comment by SaulJWu** [comment]
原来偏好设置，这样设置也行啊
[https://raw.githubusercontent.com/Thobian/typora-image/master/demo/202008/12/184051-58320.png](url)
