### ISSUE TITLE
服务器响应解析失败，请稍后重试

### ISSUE THREAD

**Issue by molzy123** [Thobian/typora-plugins-win-img#9]
想问这个插件还能用吗，直接按照步骤进行操作，好像不行，更换成github的也不可以

**Comment by Thobian** [comment]
可以用。
使用是如果遇到问题，需要你把更详细的情况反馈过来我才能给你定位，比如你的配置你的文件目录情况，单纯这样我是没法知道问题出在哪里的

**Comment by molzy123** [comment]
$.image.init({
    target:'github',
    github:{
        Token : '447bf74c2df1fb2a201b781fe0f3d7127bcf6f66', // 添加一个仅给typora使用的token 授予最小的权限（repo.public_repo） ，添加token：https://github.com/settings/tokens
        CommitterName : 'molzy123',                         // 提交人昵称，写你github的昵称
        CommitterEmail : '1299797448@qq.com',                  // 提交人邮箱，写你github的邮箱
        Repository : 'molzy123/myNote',      // github项目名，比如你的项目地址是：https://github.com/Thobian/typora-plugins-win-img  那就是后面的“Thobian/typora-plugins-win-img”
        Filepath : 'typora',                                // 图片在项目中的保存目录，可以不用提前创建目录，github提交时发现没有会自动创建
    }
});
以上就是我根据步骤配置的存储在github的代码，还配置了七牛云的，不知道是不是我配置错误了

**Comment by Thobian** [comment]
不好意思，确实由于我的问题 在之前的改动中弄出来了bug
你拉去下最新的代码，重新配置下应该OK了

**Comment by molzy123** [comment]
我刚才尝试了一下，已经解决，并且我在最新版本的typora上面进行尝试配置，也已经成功了。非常感谢
